on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: esp-idf build
        uses: jdoubleu/esp-idf-ci-action@input-esp-version-adjustment
        with:
          esp_idf_version: v4.4
          target: ESP32-c3
          path: some/path
